# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Test.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PolitiProcessApp(object):
    def setupUi(self, PolitiProcessApp):
        PolitiProcessApp.setObjectName("PolitiProcessApp")
        PolitiProcessApp.setWindowModality(QtCore.Qt.ApplicationModal)
        PolitiProcessApp.setEnabled(True)
        PolitiProcessApp.resize(1000, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PolitiProcessApp.sizePolicy().hasHeightForWidth())
        PolitiProcessApp.setSizePolicy(sizePolicy)
        PolitiProcessApp.setMinimumSize(QtCore.QSize(800, 600))
        PolitiProcessApp.setMaximumSize(QtCore.QSize(1000, 800))
        self.gridLayout = QtWidgets.QGridLayout(PolitiProcessApp)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_5 = QtWidgets.QFrame(PolitiProcessApp)
        self.frame_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(100, 100))
        self.frame_5.setMaximumSize(QtCore.QSize(600, 776))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.PlotLabel = QtWidgets.QLabel(self.frame_5)
        self.PlotLabel.setObjectName("PlotLabel")
        self.gridLayout_2.addWidget(self.PlotLabel, 0, 4, 1, 1)
        self.PlotViewer = QtWidgets.QGraphicsView(self.frame_5)
        self.PlotViewer.setObjectName("PlotViewer")
        self.gridLayout_2.addWidget(self.PlotViewer, 1, 4, 1, 1)
        self.gridLayout.addWidget(self.frame_5, 1, 4, 2, 1)
        self.ParamBrowserFrame = QtWidgets.QFrame(PolitiProcessApp)
        self.ParamBrowserFrame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.ParamBrowserFrame.setAutoFillBackground(True)
        self.ParamBrowserFrame.setStyleSheet("")
        self.ParamBrowserFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ParamBrowserFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ParamBrowserFrame.setObjectName("ParamBrowserFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ParamBrowserFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ParamBrowserWidget = QtWidgets.QWidget(self.ParamBrowserFrame)
        self.ParamBrowserWidget.setObjectName("ParamBrowserWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ParamBrowserWidget)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ParamLoadLabel = QtWidgets.QLabel(self.ParamBrowserWidget)
        self.ParamLoadLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Beirut")
        font.setPointSize(20)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.ParamLoadLabel.setFont(font)
        self.ParamLoadLabel.setObjectName("ParamLoadLabel")
        self.verticalLayout.addWidget(self.ParamLoadLabel, 0, QtCore.Qt.AlignHCenter)
        self.ParamLoadButton = QtWidgets.QPushButton(self.ParamBrowserWidget)
        self.ParamLoadButton.setEnabled(False)
        self.ParamLoadButton.setAutoDefault(False)
        self.ParamLoadButton.setDefault(False)
        self.ParamLoadButton.setFlat(False)
        self.ParamLoadButton.setObjectName("ParamLoadButton")
        self.verticalLayout.addWidget(self.ParamLoadButton)
        self.ParamSaveButton = QtWidgets.QPushButton(self.ParamBrowserWidget)
        self.ParamSaveButton.setObjectName("ParamSaveButton")
        self.verticalLayout.addWidget(self.ParamSaveButton)
        self.ParamList = QtWidgets.QListView(self.ParamBrowserWidget)
        self.ParamList.setObjectName("ParamList")
        self.verticalLayout.addWidget(self.ParamList)
        self.verticalLayout_2.addWidget(self.ParamBrowserWidget)
        self.gridLayout.addWidget(self.ParamBrowserFrame, 1, 0, 1, 1)
        self.MongoFrame = QtWidgets.QFrame(PolitiProcessApp)
        self.MongoFrame.setEnabled(True)
        self.MongoFrame.setMaximumSize(QtCore.QSize(250, 1000))
        self.MongoFrame.setMouseTracking(False)
        self.MongoFrame.setToolTip("")
        self.MongoFrame.setAutoFillBackground(False)
        self.MongoFrame.setStyleSheet("")
        self.MongoFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.MongoFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MongoFrame.setLineWidth(1)
        self.MongoFrame.setObjectName("MongoFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.MongoFrame)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.MongoLabel = QtWidgets.QLabel(self.MongoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MongoLabel.sizePolicy().hasHeightForWidth())
        self.MongoLabel.setSizePolicy(sizePolicy)
        self.MongoLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Beirut")
        font.setPointSize(20)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.MongoLabel.setFont(font)
        self.MongoLabel.setObjectName("MongoLabel")
        self.verticalLayout_3.addWidget(self.MongoLabel, 0, QtCore.Qt.AlignHCenter)
        self.MongoPanel = QtWidgets.QWidget(self.MongoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MongoPanel.sizePolicy().hasHeightForWidth())
        self.MongoPanel.setSizePolicy(sizePolicy)
        self.MongoPanel.setMinimumSize(QtCore.QSize(0, 354))
        self.MongoPanel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.MongoPanel.setObjectName("MongoPanel")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.MongoPanel)
        self.verticalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.TimeFrameLabel = QtWidgets.QLabel(self.MongoPanel)
        self.TimeFrameLabel.setObjectName("TimeFrameLabel")
        self.verticalLayout_4.addWidget(self.TimeFrameLabel)
        self.widget = QtWidgets.QWidget(self.MongoPanel)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.QueryHours = QtWidgets.QDoubleSpinBox(self.widget)
        self.QueryHours.setPrefix("")
        self.QueryHours.setDecimals(0)
        self.QueryHours.setMinimum(0.0)
        self.QueryHours.setMaximum(24.0)
        self.QueryHours.setObjectName("QueryHours")
        self.horizontalLayout.addWidget(self.QueryHours)
        self.QueryHours_2 = QtWidgets.QDoubleSpinBox(self.widget)
        self.QueryHours_2.setProperty("showGroupSeparator", False)
        self.QueryHours_2.setDecimals(0)
        self.QueryHours_2.setMinimum(0.0)
        self.QueryHours_2.setMaximum(7.0)
        self.QueryHours_2.setObjectName("QueryHours_2")
        self.horizontalLayout.addWidget(self.QueryHours_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.widget)
        self.QueryBlue = QtWidgets.QCheckBox(self.MongoPanel)
        self.QueryBlue.setObjectName("QueryBlue")
        self.verticalLayout_4.addWidget(self.QueryBlue)
        self.QueryRed = QtWidgets.QCheckBox(self.MongoPanel)
        self.QueryRed.setObjectName("QueryRed")
        self.verticalLayout_4.addWidget(self.QueryRed)
        self.QueryArticles = QtWidgets.QRadioButton(self.MongoPanel)
        self.QueryArticles.setObjectName("QueryArticles")
        self.verticalLayout_4.addWidget(self.QueryArticles)
        self.line = QtWidgets.QFrame(self.MongoPanel)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.QueryRunButton = QtWidgets.QCommandLinkButton(self.MongoPanel)
        self.QueryRunButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QueryRunButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.QueryRunButton.setAutoFillBackground(False)
        self.QueryRunButton.setText("Run Query")
        self.QueryRunButton.setIconSize(QtCore.QSize(40, 40))
        self.QueryRunButton.setAutoDefault(True)
        self.QueryRunButton.setObjectName("QueryRunButton")
        self.verticalLayout_4.addWidget(self.QueryRunButton)
        self.QueryAll = QtWidgets.QCommandLinkButton(self.MongoPanel)
        self.QueryAll.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QueryAll.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.QueryAll.setAutoFillBackground(True)
        self.QueryAll.setText("Query All")
        self.QueryAll.setIconSize(QtCore.QSize(40, 40))
        self.QueryAll.setAutoDefault(True)
        self.QueryAll.setObjectName("QueryAll")
        self.verticalLayout_4.addWidget(self.QueryAll)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.progressBar = QtWidgets.QProgressBar(self.MongoPanel)
        self.progressBar.setProperty("value", 80)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.verticalLayout_3.addWidget(self.MongoPanel)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.gridLayout.addWidget(self.MongoFrame, 2, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(PolitiProcessApp)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.toolBox = QtWidgets.QToolBox(self.widget_2)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 394, 684))
        self.page.setObjectName("page")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 394, 684))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.verticalLayout_5.addWidget(self.toolBox)
        self.gridLayout.addWidget(self.widget_2, 1, 1, 2, 1)

        self.retranslateUi(PolitiProcessApp)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PolitiProcessApp)

    def retranslateUi(self, PolitiProcessApp):
        _translate = QtCore.QCoreApplication.translate
        PolitiProcessApp.setWindowTitle(_translate("PolitiProcessApp", "Form"))
        self.PlotLabel.setText(_translate("PolitiProcessApp", "Plot Label"))
        self.ParamLoadLabel.setText(_translate("PolitiProcessApp", "Parameter Browser"))
        self.ParamLoadButton.setText(_translate("PolitiProcessApp", "Load"))
        self.ParamSaveButton.setText(_translate("PolitiProcessApp", "Save"))
        self.MongoLabel.setText(_translate("PolitiProcessApp", "Mongo Stuff"))
        self.TimeFrameLabel.setText(_translate("PolitiProcessApp", "Time Frame to Query"))
        self.QueryHours.setSuffix(_translate("PolitiProcessApp", "  Hours"))
        self.QueryHours_2.setSuffix(_translate("PolitiProcessApp", "  Days"))
        self.QueryBlue.setText(_translate("PolitiProcessApp", "Blue"))
        self.QueryRed.setText(_translate("PolitiProcessApp", "Red"))
        self.QueryArticles.setText(_translate("PolitiProcessApp", "Articles"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("PolitiProcessApp", "Page 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("PolitiProcessApp", "Page 2"))

